#!/bin/bash
#
# Liver disease exploratory data analysis.
#

PROMPT=ldc
VENV=.$PROMPT

# Create virtual environment.
uv venv $VENV --prompt $PROMPT --clear

# Activate virtual environment.
source $VENV/bin/activate

# Install dependencies.
uv pip install -e . --quiet

# Enable command-line autocompletion for the `liver` command.
eval "$(register-python-argcomplete liver)"
