#!/bin/bash
#
# Liver disease exploratory data analysis.
#

if [[ $(which uv) == "" ]]; then
    echo "Please install uv and try again."
    echo "Command: curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi

PROMPT=ldc
VENV=.$PROMPT

# Create virtual environment.
uv venv $VENV --prompt $PROMPT --clear

# Activate virtual environment.
source $VENV/bin/activate

# Install dependencies.
uv pip install -e . --quiet

# Enable command-line autocompletion for the `liver` command.
eval "$(register-python-argcomplete liver)"
